### ISSUE TITLE
Auto-update not working

### ISSUE THREAD

**Issue by uxleo-com** [clupascu/GoogleApps_SumByColor#2]
For some reason update trick is not working as desribed. Have there been any changes in the script?

**Comment by uxleo-com** [comment]
Says
#Error! Bad value (line: 2)

**Comment by clupascu** [comment]
Can you please provide more details?

* What is the formula you used?
* Are the values in the target cells numeric?
* Are you using the script from this repository, or the one from Google's script gallery?

**Comment by uxleo-com** [comment]
Sure. Formula I'm using is =sumWhereBackgroundColorIs("#ffffff","C3:C9")
is works perfectly. But when I'm adding =sumWhereBackgroundColorIs("#ffffff","C3:C9", C3:C9) I'm getting nasty error: http://take.ms/ph1BR

**Comment by clupascu** [comment]
I found the reason behind the error: it's the new functionality that allows referencing cells in a different spreadsheet.

The third argument is now an optional spreadsheet name. If that's not present, the current spreadsheet is used.

The quick fix for your problem is to pass and empty string (`""`) as a third parameter and then do the `C3:C9` trick:

    =sumWhereBackgroundColorIs("#ffffff","C3:C9", "", C3:C9)

The formula above should work in your case. This is starting to get ugly though; I'm searching to see if there's a better way to write the formula.

Thanks for pointing out the error!

**Comment by clupascu** [comment]
Updated documentation in 7a924a013738018638b6993c1bd352d69cfead7d.
